version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: screenwatcher_web
    # Poprawione: screenwatcher_project zamiast screenwatcher
    command: gunicorn screenwatcher_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: screenwatcher_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  redis:
    image: redis:7
    container_name: screenwatcher_redis
    # Brak sekcji ports tutaj rozwiÄ…zuje konflikt portu 6379

  celery_worker:
    build: .
    container_name: screenwatcher_celery_worker
    # Poprawione: screenwatcher_project
    command: celery -A screenwatcher_project worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    container_name: screenwatcher_celery_beat
    # Poprawione: screenwatcher_project
    command: celery -A screenwatcher_project beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
