apiVersion: v1
kind: Service
metadata:
  name: {{ include "rae-memory.fullname" . }}-api
  labels:
    {{- include "rae-memory.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.memoryApi.service.type }}
  ports:
    - port: {{ .Values.memoryApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rae-memory.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
